---

- hosts: all
  become: true
  tasks:

  # - name: update repository index
  #   apt:
  #    update_cache: yes
  #   when: ansible_distribution in ["Ubuntu", "Debian"]

#  - name: install apache2 package
#    apt:
#      name: apache2
#    when: ansible_distribution in ["Ubuntu", "Debian"]

# - name: add php support for apache
#   apt:
#     name: libapache2-mod-php
#     state: latest
#   when: ansible_distribution == "Ubuntu"

#moze i ovako - lista paketa umesto jednog
  - name: add apache2 and php support for apache
    apt:
      name: 
        - libapache2-mod-php
        - apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add apache2 and php support for apache
    dnf:
      update_cache: yes
      name: 
        - httpd
      state: latest
    when: ansible_distribution == "CentOS"

